src/delay/delay.o: ../src/delay/delay.c
src/delay/delay.o: ../src/delay/delay.h
src/delay/delay.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/assert.h
src/delay/delay.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/alt_clock_manager.h
src/delay/delay.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/hwlib.h
src/delay/delay.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stddef.h
src/delay/delay.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stdbool.h
src/delay/delay.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stdint.h
src/delay/delay.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/alt_hwlibs_ver.h
src/delay/delay.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/alt_clock_group.h
src/delay/delay.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/socal/alt_clkmgr.h
src/delay/delay.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/alt_globaltmr.h
