src/uart/alt_16550_uart.o: ../src/uart/alt_16550_uart.c
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/alt_16550_uart.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/hwlib.h
src/uart/alt_16550_uart.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stddef.h
src/uart/alt_16550_uart.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stdbool.h
src/uart/alt_16550_uart.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stdint.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/alt_hwlibs_ver.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/alt_clock_manager.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/alt_clock_group.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/socal/alt_clkmgr.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/socal/alt_rstmgr.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/socal/alt_uart.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/socal/hps.h
src/uart/alt_16550_uart.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/socal/socal.h
