src/main.o: ../src/main.c
src/main.o: ../src/bluetooth/bluetooth.h
src/main.o: ../src/wifi/wifi.h
src/main.o: ../src/common.h
src/main.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stdio.h
src/main.o: ../src/wifi/wifi.h
src/main.o: ../src/uart/uart.h
src/main.o: ../src/delay/delay.h
src/main.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/assert.h
src/main.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/alt_clock_manager.h
src/main.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/hwlib.h
src/main.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stddef.h
src/main.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stdbool.h
src/main.o: /usr/local/DS-5/sw/ARMCompiler5.05u1/bin/../include/stdint.h
src/main.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/alt_hwlibs_ver.h
src/main.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/alt_clock_group.h
src/main.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/soc_cv_av/socal/alt_clkmgr.h
src/main.o: /home/jared/Desktop/smartcart/de1-hardware/project/arm/ARM_SYSTEM/lib/hwlib/alt_globaltmr.h
src/main.o: ../src/hx711/hx711.h
